### ISSUE TITLE
About RGB Led Strip Version

### ISSUE THREAD

**Issue by kayagultekin** [Sunoo/homebridge-gpio-rgbw-ledstrip#42]
Thanks for the great plugin and definitive install instructions..

I have tested nearly all the rgb led strip homebridge plugins to no avail. Most of them depended either on pigpio library v0.6.2 or node version compatible with v8. Only this plugin really works on my installation of official homebridge image. As I have an rgb led instead of rgbw one I tried to modify this library to rgb led strip locally. I have removed every code that is related to white color. As a result all the colors are working except for white..

Can you direct me to the right direction or provide an rgb version of this plugin if that is not too time consuming for you..

Thanks in advance.

**Comment by Sunoo** [comment]
I had actually considered supporting RGB strips, but assumed they were largely covered by other plugins, so never bothered.

I could probably support it fairly easily. Since there seems to actually be a use for that, I’ll look into adding it maybe this weekend.

**Comment by kayagultekin** [comment]
Hello again!

I called at to tell you I have just figured out how to modify your plugin to work with RGB Ledstrip. I hope I wrote before you worked on this! 

Thank you for your kind approach to my help request! I have learnt a lot by example, thank you for that too.

I am thinking to publish the resulting plugin to npm registry along with an attribution to you and your plugin. Although the licence permits it I want to ask:  what do you say?

**Comment by Sunoo** [comment]
I had not had a chance to start work on the changes, so that’s convenient. And sure, go ahead and publish your RGB-only version, my code is specifically licensed to allow for that.
